export const SET_LOADING = "SET_LOADING";

export const GET_TODOS = "GET_TODOS";
export const GET_TODOS_REQUEST = "GET_TODOS_REQUEST";

export const GET_TODO = "GET_TODO";
export const GET_TODO_REQUEST = "GET_TODO_REQUEST";

export const CREATE_TODO = "CREATE_TODO";
export const CREATE_TODO_REQUEST = "CREATE_TODO_REQUEST";


export const DELETE_TODO = "DELETE_TODO";
export const DELETE_TODO_REQUEST = "DELETE_TODO_REQUEST";

export const EDIT_TODO = "EDIT_TODO";
export const EDIT_TODO_REQUEST = "EDIT_TODO_REQUEST";

export const CLEAR_TODO = "CLEAR_TODO";
export const CLEAR_TODO_TODOS = "CLEAR_TODO_TODOS";

export const CHANGE_TODO_STATUS = "CHANGE_TODO_STATUS";
export const CHANGE_TODO_STATUS_TODOS = "CHANGE_TODO_STATUS_TODOS";
